# .github/workflows/sitemap.yml
name: Generate Sitemap

# 1) Explicitly grant write permissions for contents (so “add-and-commit” can push)
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
      # 2) Check out the repo
      - uses: actions/checkout@v4

      # 3) Generate sitemap
      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1.10.0
        with:
          base-url-path: https://nera-w.github.io/

      # 4) Commit sitemap.xml back (now that GITHUB_TOKEN has write perms)
      - name: Commit sitemap.xml
        uses: EndBug/add-and-commit@v7
        with:
          add: 'sitemap.xml'
          message: 'chore: update sitemap'
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
